CREATE TABLE USERS (
    USERNAME VARCHAR(50) PRIMARY KEY,
    PASSWORD BINARY VARYING(64) NOT NULL,
    FULL_NAME VARCHAR(50) NOT NULL,
    PHONE VARCHAR(15) NOT NULL,
    CITY_NAME VARCHAR(30) NOT NULL,
    ROLE_ID INT NOT NULL,
    EDUCATION CHARACTER LARGE OBJECT,
    ADDING_TIME DATETIME,
    CONSTRAINT FK_USERS_CITY FOREIGN KEY (CITY_NAME) REFERENCES CITY(NAME),
    CONSTRAINT FK_USERS_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);