INSERT INTO ROLE(NAME, LIST_SPECIALISTS, SHOW_SPECIALIST, EDIT_USER, LIST_REQUESTS, SHOW_REQUEST, ADD_REQUEST, EDIT_REQUEST, ADD_ANNOUNCEMENT, EDIT_ANNOUNCEMENT, ADD_CITY, ADD_CATEGORY)
VALUES('Обычный пользователь', false, true, true, true, false, true, false, false, false, false, false);
INSERT INTO ROLE(NAME, LIST_SPECIALISTS, SHOW_SPECIALIST, EDIT_USER, LIST_REQUESTS, SHOW_REQUEST, ADD_REQUEST, EDIT_REQUEST, ADD_ANNOUNCEMENT, EDIT_ANNOUNCEMENT, ADD_CITY, ADD_CATEGORY)
VALUES('Администратор', true, true, false, true, true, false, true, false, false, true, true);
INSERT INTO ROLE(NAME, LIST_SPECIALISTS, SHOW_SPECIALIST, EDIT_USER, LIST_REQUESTS, SHOW_REQUEST, ADD_REQUEST, EDIT_REQUEST, ADD_ANNOUNCEMENT, EDIT_ANNOUNCEMENT, ADD_CITY, ADD_CATEGORY)
VALUES('Специалист', false, true, true, true, false, true, false, true, true, false, false);

INSERT INTO CITY(NAME) VALUES('Ярославль');
INSERT INTO CITY(NAME) VALUES('Москва');
INSERT INTO CITY(NAME) VALUES('Кострома');
INSERT INTO CITY(NAME) VALUES('Екатеринбург');
INSERT INTO CITY(NAME) VALUES('Рыбинск');
INSERT INTO CITY(NAME) VALUES('Тутаев');
INSERT INTO CITY(NAME) VALUES('Данилов');
INSERT INTO CITY(NAME) VALUES('Углич');
INSERT INTO CITY(NAME) VALUES('Санкт-Петербург');
INSERT INTO CITY(NAME) VALUES('Любим');
INSERT INTO CITY(NAME) VALUES('Ростов');
INSERT INTO CITY(NAME) VALUES('Смоленск');
INSERT INTO CITY(NAME) VALUES('Воронеж');
INSERT INTO CITY(NAME) VALUES('Гаврилов-Ям');

INSERT INTO CATEGORY(NAME, ADDING_TIME) VALUES('Образование', CURRENT_DATE + CURRENT_TIME);
INSERT INTO CATEGORY(NAME, ADDING_TIME) VALUES('Транспорт', CURRENT_DATE + CURRENT_TIME);
INSERT INTO CATEGORY(NAME, ADDING_TIME) VALUES('Бытовая техника', CURRENT_DATE + CURRENT_TIME);
INSERT INTO CATEGORY(NAME, ADDING_TIME) VALUES('Здравоохранение', CURRENT_DATE + CURRENT_TIME);
INSERT INTO CATEGORY(NAME, ADDING_TIME) VALUES('Парикмахерские', CURRENT_DATE + CURRENT_TIME);
INSERT INTO CATEGORY(NAME, ADDING_TIME) VALUES('Секретарские', CURRENT_DATE + CURRENT_TIME);
INSERT INTO CATEGORY(NAME, ADDING_TIME) VALUES('Разработка', CURRENT_DATE + CURRENT_TIME);
INSERT INTO CATEGORY(NAME, ADDING_TIME) VALUES('Тестирование', CURRENT_DATE + CURRENT_TIME);
INSERT INTO CATEGORY(NAME, ADDING_TIME) VALUES('Менеджмент', CURRENT_DATE + CURRENT_TIME);
INSERT INTO CATEGORY(NAME, ADDING_TIME) VALUES('Консультационные', CURRENT_DATE + CURRENT_TIME);
INSERT INTO CATEGORY(NAME, ADDING_TIME) VALUES('Психологические', CURRENT_DATE + CURRENT_TIME);
INSERT INTO CATEGORY(NAME, ADDING_TIME) VALUES('Юридические', CURRENT_DATE + CURRENT_TIME);
INSERT INTO CATEGORY(NAME, ADDING_TIME) VALUES('Экономические', CURRENT_DATE + CURRENT_TIME);
